/* 
ORA-00001: unique constraint (SYS.I_PLSCOPE_SIG_IDENTIFIER$) violated
------
ALTER SESSION SET PLSCOPE_SETTINGS = 'IDENTIFIERS:NONE';
-----
*/

ALTER SESSION SET PLSCOPE_SETTINGS = 'IDENTIFIERS:NONE';
DROP TABLE CATEGORIA;
DROP TABLE PERSONA;
DROP TABLE TELEFONO;
DROP TABLE USUARIO;
DROP TABLE NOTA;
DROP TABLE TIPO_USUARIO;
DROP TABLE MENU;


CREATE TABLE TIPO_USUARIO
(
    ID_TIPO_USUARIO INT NOT NULL,
    DETALLE VARCHAR2(60),
    ESTADO CHAR(1) DEFAULT '1' CONSTRAINT "CHK_ESTADO_TIPO_USUARIO" CHECK (ESTADO IN('0','1')),
    CONSTRAINT PK_TIPO_USUARIO PRIMARY KEY(ID_TIPO_USUARIO)
);

CREATE TABLE CATEGORIA
( 
  ID_CATEGORIA INT NOT NULL,
  NOMBRES VARCHAR2(20) NOT NULL,
  ESTADO CHAR(1) DEFAULT '1' CONSTRAINT "CHK_ESTADO_CATEGORIA" CHECK (ESTADO IN('0','1')) ,
  CONSTRAINT PK_CATEGORIA PRIMARY KEY(ID_CATEGORIA)
);

CREATE TABLE PERSONA
( 
  ID_PERSONA INT NOT NULL CONSTRAINT PK_PERSONA PRIMARY KEY,
  CEDULA char(12) NOT NULL,
  NOMBRES VARCHAR2(20) NOT NULL,
  APELLIDOS VARCHAR2(20) NOT NULL,
  SEXO CHAR(1) CONSTRAINT CH_PERSONA_SEXO CHECK(SEXO IN ('M','F')),
  CONSTRAINT "UI_PERSONA_NOMBRES" UNIQUE ("NOMBRES", "APELLIDOS"),
  CONSTRAINT "UI_PERSONA_CEDULA" UNIQUE ("CEDULA")
);

CREATE TABLE TELEFONO
(
    ID_TELEFONO INT NOT NULL,
    ID_PERSONA INT NOT NULL,
    NUMERO NVARCHAR2(20),
    CONSTRAINT PK_TELEFONO PRIMARY KEY(ID_TELEFONO),
    CONSTRAINT FK_TELEFONO_PERSONA FOREIGN KEY(ID_PERSONA) REFERENCES PERSONA(ID_PERSONA)
);
/*CAMBIE A NOT NULL*/
CREATE TABLE USUARIO
(
     ID_USUARIO INT NOT NULL,
     USUARIO NVARCHAR2(20) NOT NULL,
     CLAVE NVARCHAR2(20) NOT NULL,
     -- cambiar en el modelo
     ID_TIPO_USUARIO INT NOT NULL,
     ESTADO CHAR(1) DEFAULT '1' CONSTRAINT "CHK_ESTADO_USUARIO" CHECK (ESTADO IN('0','1')) ,
     ID_PERSONA INT NOT NULL,
     CONSTRAINT PK_USUARIO PRIMARY KEY(ID_USUARIO),
     CONSTRAINT FK_USUARIO_PERSONA FOREIGN KEY(ID_PERSONA) REFERENCES PERSONA(ID_PERSONA),
     CONSTRAINT FK_USUARIO_TIPO_USUARIO FOREIGN KEY(ID_TIPO_USUARIO) REFERENCES TIPO_USUARIO(ID_TIPO_USUARIO),
      CONSTRAINT "UI_PERSONA_CEDULA" UNIQUE ("USUARIO")
);

CREATE TABLE NOTA
(
    ID_NOTA INT NOT NULL,
    ID_PERSONA INT NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    NUMERO NVARCHAR2(20),
    ENCABEZADO NVARCHAR2(50),
    CUERPO NVARCHAR2(500),
    FECHA DATE,
    COMENTARIO_ADMIN NVARCHAR2(100),
    VALORACION INT CONSTRAINT CHK_VALORACION CHECK(VALORACION BETWEEN 1 AND 5) NOT NULL,
    CONSTRAINT PK_NOTA PRIMARY KEY(ID_NOTA),
    CONSTRAINT FK_NOTA_PERSONA FOREIGN KEY(ID_PERSONA) REFERENCES PERSONA(ID_PERSONA),
    CONSTRAINT FK_NOTA_CATEGORIA FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

/*CREACION DE UN MENU DINAMICO*/



CREATE TABLE MENU
(
    ID_MENU INT NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    URL VARCHAR2(100),
    TIPO CHAR(1) CONSTRAINT CHK_MENU_TIPO CHECK(TIPO IN ('S','I')),
    ID_TIPO_USUARIO INT NOT NULL,
    ID_SUBMENU INT,
    ESTADO CHAR(1) DEFAULT '1' CONSTRAINT "CHK_MENU_ESTADO" CHECK (ESTADO IN('0','1')),
    CONSTRAINT PK_MENU PRIMARY KEY(ID_MENU),
    CONSTRAINT FK_MENU_TIPO_USUARIO FOREIGN KEY(ID_TIPO_USUARIO) REFERENCES TIPO_USUARIO(ID_TIPO_USUARIO),
    CONSTRAINT FK_MENU_MENU FOREIGN KEY(ID_SUBMENU) REFERENCES MENU(ID_MENU)
);





/*INCREMENTE PARA VERSION DE ORACLE 11*/
DROP SEQUENCE CATEGORIA_SEQUENCE;
DROP SEQUENCE PERSONA_SEQUENCE;
DROP SEQUENCE TELEFONO_SEQUENCE;
DROP SEQUENCE USUARIO_SEQUENCE;
DROP SEQUENCE NOTA_SEQUENCE;
DROP SEQUENCE TIPO_USUARIO_SEQUENCE;
DROP SEQUENCE MENU_SEQUENCE;



CREATE  SEQUENCE CATEGORIA_SEQUENCE MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE PERSONA_SEQUENCE  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE TELEFONO_SEQUENCE  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE USUARIO_SEQUENCE  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE NOTA_SEQUENCE  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE TIPO_USUARIO_SEQUENCE  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE MENU_SEQUENCE  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;




CREATE OR REPLACE TRIGGER "CATEGORIA_ON_INSERT"
BEFORE INSERT ON CATEGORIA
FOR EACH ROW
BEGIN
  SELECT CATEGORIA_SEQUENCE.nextval
    INTO :new."ID_CATEGORIA" 
    FROM dual;
END;



CREATE OR REPLACE TRIGGER PERSONA_ON_INSERT
  BEFORE INSERT ON PERSONA
  FOR EACH ROW
BEGIN
  SELECT PERSONA_SEQUENCE.nextval
  INTO :new.ID_PERSONA
  FROM dual;
END;




CREATE OR REPLACE TRIGGER TELEFONO_ON_INSERT
  BEFORE INSERT ON TELEFONO
  FOR EACH ROW
BEGIN
  SELECT TELEFONO_SEQUENCE.nextval
  INTO :new.ID_TELEFONO
  FROM dual;
END;


CREATE OR REPLACE TRIGGER PERSONA_ON_INSERT
  BEFORE INSERT ON PERSONA
  FOR EACH ROW
BEGIN
  IF (:new.ID_PERSONA is null) THEN
      SELECT PERSONA_SEQUENCE.nextval
      INTO :new.ID_PERSONA
      FROM dual;
  END IF;
END;



CREATE OR REPLACE TRIGGER USUARIO_ON_INSERT
  BEFORE INSERT ON USUARIO
  FOR EACH ROW
BEGIN
    IF (:new.ID_USUARIO is null) THEN
      SELECT USUARIO_SEQUENCE.nextval
      INTO :new.ID_USUARIO
      FROM dual;
    END IF;
END;


CREATE OR REPLACE TRIGGER NOTA_ON_INSERT
  BEFORE INSERT ON NOTA
  FOR EACH ROW
BEGIN
  SELECT NOTA_SEQUENCE.nextval
  INTO :new.ID_NOTA
  FROM dual;
END;

CREATE OR REPLACE TRIGGER MENU_ON_INSERT
  BEFORE INSERT ON MENU
  FOR EACH ROW
BEGIN
  SELECT MENU_SEQUENCE.nextval
  INTO :new.ID_MENU
  FROM dual;
END;

CREATE OR REPLACE TRIGGER TIPO_USUARIO_ON_INSERT
  BEFORE INSERT ON TIPO_USUARIO
  FOR EACH ROW
BEGIN
  SELECT TIPO_USUARIO_SEQUENCE.nextval
  INTO :new.ID_TIPO_USUARIO
  FROM dual;
END;
